name: MergeCraft
main: eu.ialbhost.mergecraft.MergeCraft
version: 1.0.0
api-version: 1.16
website: https://ialbhost.eu
author: Rasmus Koit
description: MergeCraft game
commands:
  points:
    description: Check your earned points in MergeCraft, can be used for various activites
    usage:
      |

      /points [ cmd ][ <user> ][ amount ]
      /points
      /points  show     user
      /points  give     user     100.0
  mergecraft:
    description: MergeCraft commands.
    usage: /mergecraft
    aliases:
      - mc
permissions:
  mergecraft.points:
    description: Allows the player to use points commands
    children:
      mergecraft.points.use: true
      mergecraft.points.give: true
      mergecraft.points.show: true
  mergecraft.points.use:
    description: Allows the player to use /points command
    default: true
  mergecraft.points.give:
    description: Allows the player to give points away to others
    default: true
  mergecraft.points.show:
    description: Allows the player to check other player points
    default: op

  mergecraft.use.bonemeal:
    description: Allows the player to use bonemeal
    default: op

  mergecraft.mc:
    description: Allows the player to use /mergecraft or /mc commands
    children:
      mergecraft.mc.use: true
      mergecraft.mc.chunk: true
      mergecraft.mc.show: true
      mergecraft.mc.show.other: true
      mergecraft.mc.shop: true
  mergecraft.mc.use:
    description: Allows the player to use /mc command
    default: true
  mergecraft.mc.chunk:
    description: Allows the player to buy chunks
    default: true
  mergecraft.mc.show:
    description: Allows the player to check their stats /mc show stats
    default: true
  mergecraft.mc.show.other:
    description: Allows the player to check others stats /mc show stats <name>
    default: op
  mergecraft.mc.shop:
    description: Allows the player to use /mc shop
    default: true


  mergecraft.*:
    description: Gives access to all MergeCraft permissions
    default: op
    children:
      mergecraft.points: true
      mergecraft.use.bonemeal: true
      mergecraft.mc: true
depend:
  - HolographicDisplays
  - ProtocolLib